dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -U pip pytest # python 2.7 requires pytest 4
  - python setup.py install
  - pip install flake8
  - pip install -r requirements-dev.txt
script:
  - flake8 slackeventsapi
  - pytest --cov-report= --cov=slackeventsapi tests
after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION
